#! /bin/sh

case "$1" in
    start)
        echo "Loading modules"
        aesdchar_load
        ;;
    stop)
        echo "Unloading modules"
        aesdchar_unload 
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0